from PyQt5 import QtCore, QtGui, QtWidgets
# Part to be added onto generated code:
import os, sys
from PyQt5.QtWidgets import QApplication
from PySide2.QtGui import QWindow
path = os.path.dirname(os.path.abspath(__file__))

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(789, 593)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setWindowOpacity(0.97)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background: rgb(230, 235, 235)")
        self.centralwidget.setObjectName("centralwidget")
        self.mainframe = QtWidgets.QFrame(self.centralwidget)
        self.mainframe.setGeometry(QtCore.QRect(-10, -30, 841, 671))
        self.mainframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainframe.setObjectName("mainframe")
        self.sideframe = QtWidgets.QFrame(self.mainframe)
        self.sideframe.setGeometry(QtCore.QRect(20, 40, 231, 571))
        self.sideframe.setStyleSheet("background: rgb(241, 246, 246);\n"
"border-style: outset;\n"
"border-radius: 30px;\n"
"")
        self.sideframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sideframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sideframe.setObjectName("sideframe")
        self.mainicon = QtWidgets.QLabel(self.sideframe)
        self.mainicon.setGeometry(QtCore.QRect(20, 30, 31, 31))
        self.mainicon.setText("")
        self.mainicon.setPixmap(QtGui.QPixmap(":/testimages/testimages/worldabyssicon.png"))
        self.mainicon.setObjectName("mainicon")
        self.worldabysslabel = QtWidgets.QLabel(self.sideframe)
        self.worldabysslabel.setGeometry(QtCore.QRect(55, 27, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Marker Felt")
        font.setPointSize(24)
        font.setItalic(True)
        self.worldabysslabel.setFont(font)
        self.worldabysslabel.setObjectName("worldabysslabel")
        self.continentsbutton = QtWidgets.QPushButton(self.sideframe)
        self.continentsbutton.setGeometry(QtCore.QRect(10, 101, 171, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.continentsbutton.sizePolicy().hasHeightForWidth())
        self.continentsbutton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(18)
        self.continentsbutton.setFont(font)
        self.continentsbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.continentsbutton.setStyleSheet("")
        self.continentsbutton.setObjectName("continentsbutton")
        self.citiesbutton = QtWidgets.QPushButton(self.sideframe)
        self.citiesbutton.setGeometry(QtCore.QRect(-10, 222, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(18)
        self.citiesbutton.setFont(font)
        self.citiesbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.citiesbutton.setStyleSheet("")
        self.citiesbutton.setObjectName("citiesbutton")
        self.citiesicon = QtWidgets.QLabel(self.sideframe)
        self.citiesicon.setGeometry(QtCore.QRect(30, 240, 16, 16))
        self.citiesicon.setText("")
        self.citiesicon.setPixmap(QtGui.QPixmap(":/testimages/testimages/cityicon.png"))
        self.citiesicon.setObjectName("citiesicon")
        self.continenticon = QtWidgets.QLabel(self.sideframe)
        self.continenticon.setGeometry(QtCore.QRect(30, 117, 16, 21))
        self.continenticon.setText("")
        self.continenticon.setPixmap(QtGui.QPixmap(":/testimages/testimages/continenticon.png"))
        self.continenticon.setObjectName("continenticon")
        self.countriesbutton = QtWidgets.QPushButton(self.sideframe)
        self.countriesbutton.setGeometry(QtCore.QRect(5, 163, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(18)
        self.countriesbutton.setFont(font)
        self.countriesbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.countriesbutton.setStyleSheet("")
        self.countriesbutton.setObjectName("countriesbutton")
        self.countriesicon_2 = QtWidgets.QLabel(self.sideframe)
        self.countriesicon_2.setGeometry(QtCore.QRect(30, 180, 16, 16))
        self.countriesicon_2.setText("")
        self.countriesicon_2.setPixmap(QtGui.QPixmap(":/testimages/testimages/countryicon.png"))
        self.countriesicon_2.setObjectName("countriesicon_2")
        self.frame = QtWidgets.QFrame(self.sideframe)
        self.frame.setGeometry(QtCore.QRect(10, 280, 201, 281))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_user_icon = QtWidgets.QLabel(self.frame)
        self.label_user_icon.setGeometry(QtCore.QRect(70, 220, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_user_icon.sizePolicy().hasHeightForWidth())
        self.label_user_icon.setSizePolicy(sizePolicy)
        self.label_user_icon.setMinimumSize(QtCore.QSize(60, 60))
        self.label_user_icon.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_user_icon.setFont(font)
        self.label_user_icon.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    background-color: rgb(234, 239, 239);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"}")
        self.label_user_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.label_user_icon.setObjectName("label_user_icon")
        self.pagesstacked = QtWidgets.QStackedWidget(self.mainframe)
        self.pagesstacked.setGeometry(QtCore.QRect(240, 30, 541, 1371))
        self.pagesstacked.setObjectName("pagesstacked")
        self.continentspage = QtWidgets.QWidget()
        self.continentspage.setObjectName("continentspage")
        self.searchbar = QtWidgets.QLineEdit(self.continentspage)
        self.searchbar.setGeometry(QtCore.QRect(20, 20, 461, 41))
        self.searchbar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.searchbar.setAcceptDrops(False)
        self.searchbar.setStyleSheet("background: rgba(190, 194, 194, 235);  \n"
"border-radius: 8px; \n"
"border-style: outset;\n"
"border: none;")
        self.searchbar.setFrame(False)
        self.searchbar.setClearButtonEnabled(True)
        self.searchbar.setObjectName("searchbar")
        self.plusbutton = QtWidgets.QPushButton(self.continentspage)
        self.plusbutton.setGeometry(QtCore.QRect(490, 20, 41, 41))
        self.plusbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.plusbutton.setStyleSheet("background: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-radius: 8px;")
        self.plusbutton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/testimages/testimages/addsymbol.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.plusbutton.setIcon(icon)
        self.plusbutton.setObjectName("plusbutton")
        self.asiabutton = QtWidgets.QPushButton(self.continentspage)
        self.asiabutton.setGeometry(QtCore.QRect(10, 80, 271, 181))
        self.asiabutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.asiabutton.setStyleSheet("border: none;")
        self.asiabutton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/testimages/testimages/image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.asiabutton.setIcon(icon1)
        self.asiabutton.setIconSize(QtCore.QSize(300, 160))
        self.asiabutton.setObjectName("asiabutton")
        self.asiaword = QtWidgets.QLabel(self.continentspage)
        self.asiaword.setGeometry(QtCore.QRect(90, 150, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(51)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.asiaword.setFont(font)
        self.asiaword.setStyleSheet("background: none;\n"
"color: white;")
        self.asiaword.setObjectName("asiaword")
        self.antarticabutton = QtWidgets.QPushButton(self.continentspage)
        self.antarticabutton.setGeometry(QtCore.QRect(272, 72, 271, 181))
        self.antarticabutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.antarticabutton.setStyleSheet("border: none;")
        self.antarticabutton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/testimages/testimages/image-7.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.antarticabutton.setIcon(icon2)
        self.antarticabutton.setIconSize(QtCore.QSize(320, 180))
        self.antarticabutton.setObjectName("antarticabutton")
        self.antarticaword = QtWidgets.QLabel(self.continentspage)
        self.antarticaword.setGeometry(QtCore.QRect(390, 150, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(29)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.antarticaword.setFont(font)
        self.antarticaword.setStyleSheet("background: none;\n"
"color: white;")
        self.antarticaword.setObjectName("antarticaword")
        self.usabutton = QtWidgets.QPushButton(self.continentspage)
        self.usabutton.setGeometry(QtCore.QRect(10, 260, 191, 111))
        self.usabutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.usabutton.setStyleSheet("border: none;")
        self.usabutton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/testimages/testimages/image-4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.usabutton.setIcon(icon3)
        self.usabutton.setIconSize(QtCore.QSize(300, 110))
        self.usabutton.setObjectName("usabutton")
        self.usaword = QtWidgets.QLabel(self.continentspage)
        self.usaword.setGeometry(QtCore.QRect(80, 330, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(29)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.usaword.setFont(font)
        self.usaword.setStyleSheet("background: none;\n"
"color: white;")
        self.usaword.setObjectName("usaword")
        self.africabutton = QtWidgets.QPushButton(self.continentspage)
        self.africabutton.setGeometry(QtCore.QRect(195, 256, 171, 121))
        self.africabutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.africabutton.setStyleSheet("border: none;")
        self.africabutton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/testimages/testimages/image-3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.africabutton.setIcon(icon4)
        self.africabutton.setIconSize(QtCore.QSize(300, 112))
        self.africabutton.setObjectName("africabutton")
        self.africaword = QtWidgets.QLabel(self.continentspage)
        self.africaword.setGeometry(QtCore.QRect(270, 270, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(29)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.africaword.setFont(font)
        self.africaword.setStyleSheet("background: none;\n"
"color: white;")
        self.africaword.setObjectName("africaword")
        self.southamericabutton = QtWidgets.QPushButton(self.continentspage)
        self.southamericabutton.setGeometry(QtCore.QRect(370, 262, 171, 111))
        self.southamericabutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.southamericabutton.setStyleSheet("border: none;")
        self.southamericabutton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/testimages/testimages/image-5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.southamericabutton.setIcon(icon5)
        self.southamericabutton.setIconSize(QtCore.QSize(300, 110))
        self.southamericabutton.setObjectName("southamericabutton")
        self.southamericaword = QtWidgets.QLabel(self.continentspage)
        self.southamericaword.setGeometry(QtCore.QRect(450, 310, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.southamericaword.setFont(font)
        self.southamericaword.setStyleSheet("background: none;\n"
"color: white;")
        self.southamericaword.setObjectName("southamericaword")
        self.europebutton = QtWidgets.QPushButton(self.continentspage)
        self.europebutton.setGeometry(QtCore.QRect(190, 380, 351, 191))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(51)
        self.europebutton.setFont(font)
        self.europebutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.europebutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.europebutton.setAutoFillBackground(False)
        self.europebutton.setStyleSheet("border: none;")
        self.europebutton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/testimages/testimages/europe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.europebutton.setIcon(icon6)
        self.europebutton.setIconSize(QtCore.QSize(480, 190))
        self.europebutton.setObjectName("europebutton")
        self.europeword = QtWidgets.QLabel(self.continentspage)
        self.europeword.setGeometry(QtCore.QRect(230, 530, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(41)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.europeword.setFont(font)
        self.europeword.setStyleSheet("background: none;\n"
"color: white;")
        self.europeword.setObjectName("europeword")
        self.australiabutton = QtWidgets.QPushButton(self.continentspage)
        self.australiabutton.setGeometry(QtCore.QRect(26, 382, 160, 185))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(29)
        self.australiabutton.setFont(font)
        self.australiabutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.australiabutton.setStyleSheet("background: rgb(143, 146, 146);\n"
"border-style: outset;\n"
"border-radius: 20px;\n"
"color: white;")
        self.australiabutton.setIconSize(QtCore.QSize(250, 160))
        self.australiabutton.setObjectName("australiabutton")
        self.pagesstacked.addWidget(self.continentspage)
        self.countriespage = QtWidgets.QWidget()
        self.countriespage.setObjectName("countriespage")
        self.displaytypeselector = QtWidgets.QTabWidget(self.countriespage)
        self.displaytypeselector.setGeometry(QtCore.QRect(10, 70, 521, 511))
        self.displaytypeselector.setStyleSheet("background: rgb(242, 247, 247)")
        self.displaytypeselector.setObjectName("displaytypeselector")
        self.byflag = QtWidgets.QWidget()
        self.byflag.setObjectName("byflag")
        self.scrollArea = QtWidgets.QScrollArea(self.byflag)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 511, 481))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -247, 511, 728))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 11, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 4, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 11, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 1, 1, 1)
        self.belgiumbutton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.belgiumbutton.sizePolicy().hasHeightForWidth())
        self.belgiumbutton.setSizePolicy(sizePolicy)
        self.belgiumbutton.setStyleSheet("background: none;\n"
"border: none;")
        self.belgiumbutton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/countryicons/testimages/countryicons/belgiumicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.belgiumbutton.setIcon(icon7)
        self.belgiumbutton.setIconSize(QtCore.QSize(80, 80))
        self.belgiumbutton.setObjectName("belgiumbutton")
        self.gridLayout.addWidget(self.belgiumbutton, 4, 3, 1, 1)
        self.chinabutton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chinabutton.sizePolicy().hasHeightForWidth())
        self.chinabutton.setSizePolicy(sizePolicy)
        self.chinabutton.setStyleSheet("background: none;\n"
"border: none;")
        self.chinabutton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/countryicons/testimages/countryicons/chinaicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chinabutton.setIcon(icon8)
        self.chinabutton.setIconSize(QtCore.QSize(80, 80))
        self.chinabutton.setObjectName("chinabutton")
        self.gridLayout.addWidget(self.chinabutton, 6, 1, 1, 1)
        self.germanybutton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.germanybutton.sizePolicy().hasHeightForWidth())
        self.germanybutton.setSizePolicy(sizePolicy)
        self.germanybutton.setStyleSheet("background: none;\n"
"border: none;")
        self.germanybutton.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/countryicons/testimages/countryicons/germanyicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.germanybutton.setIcon(icon9)
        self.germanybutton.setIconSize(QtCore.QSize(80, 80))
        self.germanybutton.setObjectName("germanybutton")
        self.gridLayout.addWidget(self.germanybutton, 6, 3, 1, 1)
        self.americabutton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.americabutton.sizePolicy().hasHeightForWidth())
        self.americabutton.setSizePolicy(sizePolicy)
        self.americabutton.setStyleSheet("background: none;\n"
"border: none;")
        self.americabutton.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/countryicons/testimages/countryicons/americaicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.americabutton.setIcon(icon10)
        self.americabutton.setIconSize(QtCore.QSize(80, 80))
        self.americabutton.setObjectName("americabutton")
        self.gridLayout.addWidget(self.americabutton, 4, 2, 1, 1)
        self.canadabutton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canadabutton.sizePolicy().hasHeightForWidth())
        self.canadabutton.setSizePolicy(sizePolicy)
        self.canadabutton.setStyleSheet("background: none;\n"
"border: none;")
        self.canadabutton.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/countryicons/testimages/countryicons/canadaicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.canadabutton.setIcon(icon11)
        self.canadabutton.setIconSize(QtCore.QSize(80, 80))
        self.canadabutton.setObjectName("canadabutton")
        self.gridLayout.addWidget(self.canadabutton, 4, 4, 1, 1)
        self.japanbutton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.japanbutton.sizePolicy().hasHeightForWidth())
        self.japanbutton.setSizePolicy(sizePolicy)
        self.japanbutton.setStyleSheet("background: none;\n"
"border: none;")
        self.japanbutton.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/countryicons/testimages/countryicons/japanicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.japanbutton.setIcon(icon12)
        self.japanbutton.setIconSize(QtCore.QSize(80, 80))
        self.japanbutton.setObjectName("japanbutton")
        self.gridLayout.addWidget(self.japanbutton, 6, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 2, 1, 1)
        self.finlandbutton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.finlandbutton.sizePolicy().hasHeightForWidth())
        self.finlandbutton.setSizePolicy(sizePolicy)
        self.finlandbutton.setStyleSheet("background: none;\n"
"border: none;")
        self.finlandbutton.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/countryicons/testimages/countryicons/finlandicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.finlandbutton.setIcon(icon13)
        self.finlandbutton.setIconSize(QtCore.QSize(80, 80))
        self.finlandbutton.setObjectName("finlandbutton")
        self.gridLayout.addWidget(self.finlandbutton, 6, 2, 1, 1)
        self.brazilbutton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brazilbutton.sizePolicy().hasHeightForWidth())
        self.brazilbutton.setSizePolicy(sizePolicy)
        self.brazilbutton.setStyleSheet("background: none;\n"
"border: none;")
        self.brazilbutton.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/countryicons/testimages/countryicons/brazilicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.brazilbutton.setIcon(icon14)
        self.brazilbutton.setIconSize(QtCore.QSize(80, 80))
        self.brazilbutton.setObjectName("brazilbutton")
        self.gridLayout.addWidget(self.brazilbutton, 4, 1, 1, 1)
        self.northkoreabutton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.northkoreabutton.sizePolicy().hasHeightForWidth())
        self.northkoreabutton.setSizePolicy(sizePolicy)
        self.northkoreabutton.setStyleSheet("background: none;\n"
"border: none;")
        self.northkoreabutton.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/countryicons/testimages/countryicons/northkoreaicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.northkoreabutton.setIcon(icon15)
        self.northkoreabutton.setIconSize(QtCore.QSize(80, 80))
        self.northkoreabutton.setObjectName("northkoreabutton")
        self.gridLayout.addWidget(self.northkoreabutton, 8, 1, 1, 1)
        self.singaporebutton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.singaporebutton.sizePolicy().hasHeightForWidth())
        self.singaporebutton.setSizePolicy(sizePolicy)
        self.singaporebutton.setStyleSheet("background: none;\n"
"border: none;")
        self.singaporebutton.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/countryicons/testimages/countryicons/singaporeicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.singaporebutton.setIcon(icon16)
        self.singaporebutton.setIconSize(QtCore.QSize(80, 80))
        self.singaporebutton.setObjectName("singaporebutton")
        self.gridLayout.addWidget(self.singaporebutton, 8, 3, 1, 1)
        self.georgiabutton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.georgiabutton.sizePolicy().hasHeightForWidth())
        self.georgiabutton.setSizePolicy(sizePolicy)
        self.georgiabutton.setStyleSheet("background: none;\n"
"border: none;")
        self.georgiabutton.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/countryicons/testimages/countryicons/georgiaicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.georgiabutton.setIcon(icon17)
        self.georgiabutton.setIconSize(QtCore.QSize(80, 80))
        self.georgiabutton.setObjectName("georgiabutton")
        self.gridLayout.addWidget(self.georgiabutton, 12, 2, 1, 1)
        self.southkoreabutton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.southkoreabutton.sizePolicy().hasHeightForWidth())
        self.southkoreabutton.setSizePolicy(sizePolicy)
        self.southkoreabutton.setStyleSheet("background: none;\n"
"border: none;")
        self.southkoreabutton.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/countryicons/testimages/countryicons/southkoreaicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.southkoreabutton.setIcon(icon18)
        self.southkoreabutton.setIconSize(QtCore.QSize(80, 80))
        self.southkoreabutton.setObjectName("southkoreabutton")
        self.gridLayout.addWidget(self.southkoreabutton, 10, 3, 1, 1)
        self.czechbutton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.czechbutton.sizePolicy().hasHeightForWidth())
        self.czechbutton.setSizePolicy(sizePolicy)
        self.czechbutton.setStyleSheet("background: none;\n"
"border: none;")
        self.czechbutton.setText("")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/countryicons/testimages/countryicons/czechicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.czechbutton.setIcon(icon19)
        self.czechbutton.setIconSize(QtCore.QSize(80, 80))
        self.czechbutton.setObjectName("czechbutton")
        self.gridLayout.addWidget(self.czechbutton, 10, 2, 1, 1)
        self.saudiarabiabutton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saudiarabiabutton.sizePolicy().hasHeightForWidth())
        self.saudiarabiabutton.setSizePolicy(sizePolicy)
        self.saudiarabiabutton.setStyleSheet("background: none;\n"
"border: none;")
        self.saudiarabiabutton.setText("")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/countryicons/testimages/countryicons/saudiarabiaicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saudiarabiabutton.setIcon(icon20)
        self.saudiarabiabutton.setIconSize(QtCore.QSize(80, 80))
        self.saudiarabiabutton.setObjectName("saudiarabiabutton")
        self.gridLayout.addWidget(self.saudiarabiabutton, 8, 2, 1, 1)
        self.italybutton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.italybutton.sizePolicy().hasHeightForWidth())
        self.italybutton.setSizePolicy(sizePolicy)
        self.italybutton.setStyleSheet("background: none;\n"
"border: none;")
        self.italybutton.setText("")
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/countryicons/testimages/countryicons/italyicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.italybutton.setIcon(icon21)
        self.italybutton.setIconSize(QtCore.QSize(80, 80))
        self.italybutton.setObjectName("italybutton")
        self.gridLayout.addWidget(self.italybutton, 12, 3, 1, 1)
        self.spainbutton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spainbutton.sizePolicy().hasHeightForWidth())
        self.spainbutton.setSizePolicy(sizePolicy)
        self.spainbutton.setStyleSheet("background: none;\n"
"border: none;")
        self.spainbutton.setText("")
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/countryicons/testimages/countryicons/spainicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.spainbutton.setIcon(icon22)
        self.spainbutton.setIconSize(QtCore.QSize(80, 80))
        self.spainbutton.setObjectName("spainbutton")
        self.gridLayout.addWidget(self.spainbutton, 8, 4, 1, 1)
        self.argentinabutton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.argentinabutton.sizePolicy().hasHeightForWidth())
        self.argentinabutton.setSizePolicy(sizePolicy)
        self.argentinabutton.setStyleSheet("background: none;\n"
"border: none;")
        self.argentinabutton.setText("")
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/countryicons/testimages/countryicons/argentinaicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.argentinabutton.setIcon(icon23)
        self.argentinabutton.setIconSize(QtCore.QSize(80, 80))
        self.argentinabutton.setObjectName("argentinabutton")
        self.gridLayout.addWidget(self.argentinabutton, 10, 4, 1, 1)
        self.russiabutton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.russiabutton.sizePolicy().hasHeightForWidth())
        self.russiabutton.setSizePolicy(sizePolicy)
        self.russiabutton.setStyleSheet("background: none;\n"
"border: none;")
        self.russiabutton.setText("")
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/countryicons/testimages/countryicons/russiaicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.russiabutton.setIcon(icon24)
        self.russiabutton.setIconSize(QtCore.QSize(80, 80))
        self.russiabutton.setObjectName("russiabutton")
        self.gridLayout.addWidget(self.russiabutton, 10, 1, 1, 1)
        self.malaysiabutton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.malaysiabutton.sizePolicy().hasHeightForWidth())
        self.malaysiabutton.setSizePolicy(sizePolicy)
        self.malaysiabutton.setStyleSheet("background: none;\n"
"border: none;")
        self.malaysiabutton.setText("")
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/countryicons/testimages/countryicons/malaysiaicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.malaysiabutton.setIcon(icon25)
        self.malaysiabutton.setIconSize(QtCore.QSize(80, 80))
        self.malaysiabutton.setObjectName("malaysiabutton")
        self.gridLayout.addWidget(self.malaysiabutton, 12, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 13, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 13, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 7, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 9, 4, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 9, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 11, 4, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 13, 4, 1, 1)
        self.netherlandsbutton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.netherlandsbutton.sizePolicy().hasHeightForWidth())
        self.netherlandsbutton.setSizePolicy(sizePolicy)
        self.netherlandsbutton.setStyleSheet("background: none;\n"
"border: none;")
        self.netherlandsbutton.setText("")
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/countryicons/testimages/countryicons/netherlandsicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.netherlandsbutton.setIcon(icon26)
        self.netherlandsbutton.setIconSize(QtCore.QSize(80, 80))
        self.netherlandsbutton.setObjectName("netherlandsbutton")
        self.gridLayout.addWidget(self.netherlandsbutton, 14, 1, 1, 1)
        self.indonesiabutton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.indonesiabutton.sizePolicy().hasHeightForWidth())
        self.indonesiabutton.setSizePolicy(sizePolicy)
        self.indonesiabutton.setStyleSheet("background: none;\n"
"border: none;")
        self.indonesiabutton.setText("")
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/countryicons/testimages/countryicons/indonesiaicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.indonesiabutton.setIcon(icon27)
        self.indonesiabutton.setIconSize(QtCore.QSize(80, 80))
        self.indonesiabutton.setObjectName("indonesiabutton")
        self.gridLayout.addWidget(self.indonesiabutton, 14, 3, 1, 1)
        self.austriabutton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.austriabutton.sizePolicy().hasHeightForWidth())
        self.austriabutton.setSizePolicy(sizePolicy)
        self.austriabutton.setStyleSheet("background: none;\n"
"border: none;")
        self.austriabutton.setText("")
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/countryicons/testimages/countryicons/austriaicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.austriabutton.setIcon(icon28)
        self.austriabutton.setIconSize(QtCore.QSize(80, 80))
        self.austriabutton.setObjectName("austriabutton")
        self.gridLayout.addWidget(self.austriabutton, 14, 4, 1, 1)
        self.greecebutton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.greecebutton.sizePolicy().hasHeightForWidth())
        self.greecebutton.setSizePolicy(sizePolicy)
        self.greecebutton.setStyleSheet("background: none;\n"
"border: none;")
        self.greecebutton.setText("")
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/countryicons/testimages/countryicons/greeceicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.greecebutton.setIcon(icon29)
        self.greecebutton.setIconSize(QtCore.QSize(80, 80))
        self.greecebutton.setObjectName("greecebutton")
        self.gridLayout.addWidget(self.greecebutton, 14, 2, 1, 1)
        self.azerbaijianbutton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.azerbaijianbutton.sizePolicy().hasHeightForWidth())
        self.azerbaijianbutton.setSizePolicy(sizePolicy)
        self.azerbaijianbutton.setStyleSheet("background: none;\n"
"border: none;")
        self.azerbaijianbutton.setText("")
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/countryicons/testimages/countryicons/azerbaijianicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.azerbaijianbutton.setIcon(icon30)
        self.azerbaijianbutton.setIconSize(QtCore.QSize(80, 80))
        self.azerbaijianbutton.setObjectName("azerbaijianbutton")
        self.gridLayout.addWidget(self.azerbaijianbutton, 12, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 9, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 11, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 13, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 9, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 7, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 3, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 15, 4, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 15, 3, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 15, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 15, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.displaytypeselector.addTab(self.byflag, "")
        self.byname = QtWidgets.QWidget()
        self.byname.setObjectName("byname")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.byname)
        self.scrollArea_2.setGeometry(QtCore.QRect(10, 0, 501, 471))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 499, 556))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_27 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_2.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_2.addWidget(self.label_28)
        self.label_26 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_2.addWidget(self.label_26)
        self.label_29 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_2.addWidget(self.label_29)
        self.label_61 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_61.setFont(font)
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setObjectName("label_61")
        self.verticalLayout_2.addWidget(self.label_61)
        self.label_59 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_59.setFont(font)
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setObjectName("label_59")
        self.verticalLayout_2.addWidget(self.label_59)
        self.label_60 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_60.setFont(font)
        self.label_60.setAlignment(QtCore.Qt.AlignCenter)
        self.label_60.setObjectName("label_60")
        self.verticalLayout_2.addWidget(self.label_60)
        self.label_58 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_58.setFont(font)
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName("label_58")
        self.verticalLayout_2.addWidget(self.label_58)
        self.label_64 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_64.setFont(font)
        self.label_64.setAlignment(QtCore.Qt.AlignCenter)
        self.label_64.setObjectName("label_64")
        self.verticalLayout_2.addWidget(self.label_64)
        self.label_63 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_63.setFont(font)
        self.label_63.setAlignment(QtCore.Qt.AlignCenter)
        self.label_63.setObjectName("label_63")
        self.verticalLayout_2.addWidget(self.label_63)
        self.label_62 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_62.setFont(font)
        self.label_62.setAlignment(QtCore.Qt.AlignCenter)
        self.label_62.setObjectName("label_62")
        self.verticalLayout_2.addWidget(self.label_62)
        self.label_65 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_65.setFont(font)
        self.label_65.setAlignment(QtCore.Qt.AlignCenter)
        self.label_65.setObjectName("label_65")
        self.verticalLayout_2.addWidget(self.label_65)
        self.label_71 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_71.setFont(font)
        self.label_71.setAlignment(QtCore.Qt.AlignCenter)
        self.label_71.setObjectName("label_71")
        self.verticalLayout_2.addWidget(self.label_71)
        self.label_72 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_72.setFont(font)
        self.label_72.setAlignment(QtCore.Qt.AlignCenter)
        self.label_72.setObjectName("label_72")
        self.verticalLayout_2.addWidget(self.label_72)
        self.label_70 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_70.setFont(font)
        self.label_70.setAlignment(QtCore.Qt.AlignCenter)
        self.label_70.setObjectName("label_70")
        self.verticalLayout_2.addWidget(self.label_70)
        self.label_68 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_68.setFont(font)
        self.label_68.setAlignment(QtCore.Qt.AlignCenter)
        self.label_68.setObjectName("label_68")
        self.verticalLayout_2.addWidget(self.label_68)
        self.label_67 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_67.setFont(font)
        self.label_67.setAlignment(QtCore.Qt.AlignCenter)
        self.label_67.setObjectName("label_67")
        self.verticalLayout_2.addWidget(self.label_67)
        self.label_66 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_66.setFont(font)
        self.label_66.setAlignment(QtCore.Qt.AlignCenter)
        self.label_66.setObjectName("label_66")
        self.verticalLayout_2.addWidget(self.label_66)
        self.label_69 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_69.setFont(font)
        self.label_69.setAlignment(QtCore.Qt.AlignCenter)
        self.label_69.setObjectName("label_69")
        self.verticalLayout_2.addWidget(self.label_69)
        self.label_73 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_73.setFont(font)
        self.label_73.setAlignment(QtCore.Qt.AlignCenter)
        self.label_73.setObjectName("label_73")
        self.verticalLayout_2.addWidget(self.label_73)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.displaytypeselector.addTab(self.byname, "")
        self.searchbar_2 = QtWidgets.QLineEdit(self.countriespage)
        self.searchbar_2.setGeometry(QtCore.QRect(10, 20, 531, 41))
        self.searchbar_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.searchbar_2.setAcceptDrops(False)
        self.searchbar_2.setStyleSheet("background: rgba(190, 194, 194, 235);  \n"
"border-radius: 8px; \n"
"border-style: outset;\n"
"border: none;")
        self.searchbar_2.setFrame(False)
        self.searchbar_2.setClearButtonEnabled(True)
        self.searchbar_2.setObjectName("searchbar_2")
        self.pagesstacked.addWidget(self.countriespage)
        self.canadapage = QtWidgets.QWidget()
        self.canadapage.setObjectName("canadapage")
        self.descriptionbackground = QtWidgets.QFrame(self.canadapage)
        self.descriptionbackground.setGeometry(QtCore.QRect(10, 10, 531, 571))
        self.descriptionbackground.setStyleSheet("background: rgb(245, 251, 251);\n"
"border-style: outset;\n"
"border-radius: 30px;")
        self.descriptionbackground.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.descriptionbackground.setFrameShadow(QtWidgets.QFrame.Raised)
        self.descriptionbackground.setObjectName("descriptionbackground")
        self.canadabackground = QtWidgets.QLabel(self.descriptionbackground)
        self.canadabackground.setGeometry(QtCore.QRect(0, 0, 531, 291))
        self.canadabackground.setText("")
        self.canadabackground.setPixmap(QtGui.QPixmap(":/testimages/testimages/canada.png"))
        self.canadabackground.setScaledContents(True)
        self.canadabackground.setObjectName("canadabackground")
        self.canadaword = QtWidgets.QLabel(self.descriptionbackground)
        self.canadaword.setGeometry(QtCore.QRect(10, 230, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(51)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.canadaword.setFont(font)
        self.canadaword.setStyleSheet("background: none;\n"
"color: white;")
        self.canadaword.setObjectName("canadaword")
        self.mapleleaf = QtWidgets.QLabel(self.descriptionbackground)
        self.mapleleaf.setGeometry(QtCore.QRect(200, 230, 51, 51))
        self.mapleleaf.setStyleSheet("background: none;")
        self.mapleleaf.setText("")
        self.mapleleaf.setPixmap(QtGui.QPixmap(":/testimages/testimages/mapleleaf.png"))
        self.mapleleaf.setScaledContents(True)
        self.mapleleaf.setObjectName("mapleleaf")
        self.famouswords = QtWidgets.QLabel(self.descriptionbackground)
        self.famouswords.setGeometry(QtCore.QRect(10, 310, 501, 41))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(15)
        self.famouswords.setFont(font)
        self.famouswords.setStyleSheet("background: white;\n"
"border-style: outset;\n"
"border-radius: 10px;")
        self.famouswords.setObjectName("famouswords")
        self.countrydesc = QtWidgets.QLabel(self.descriptionbackground)
        self.countrydesc.setGeometry(QtCore.QRect(10, 360, 501, 91))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        self.countrydesc.setFont(font)
        self.countrydesc.setStyleSheet("background: white;\n"
"border-style: outset;\n"
"border-radius: 10px;")
        self.countrydesc.setObjectName("countrydesc")
        self.montrealbutton = QtWidgets.QPushButton(self.descriptionbackground)
        self.montrealbutton.setGeometry(QtCore.QRect(10, 460, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.montrealbutton.setFont(font)
        self.montrealbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.montrealbutton.setStyleSheet("background: rgb(203, 207, 207);\n"
"border-style: outset;\n"
"border-radius: 10px;")
        self.montrealbutton.setObjectName("montrealbutton")
        self.torontobutton = QtWidgets.QPushButton(self.descriptionbackground)
        self.torontobutton.setGeometry(QtCore.QRect(170, 460, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.torontobutton.setFont(font)
        self.torontobutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.torontobutton.setStyleSheet("background: rgb(203, 207, 207);\n"
"border-style: outset;\n"
"border-radius: 10px;")
        self.torontobutton.setObjectName("torontobutton")
        self.vancouverbutton = QtWidgets.QPushButton(self.descriptionbackground)
        self.vancouverbutton.setGeometry(QtCore.QRect(330, 460, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.vancouverbutton.setFont(font)
        self.vancouverbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vancouverbutton.setStyleSheet("background: rgb(203, 207, 207);\n"
"border-style: outset;\n"
"border-radius: 10px;")
        self.vancouverbutton.setObjectName("vancouverbutton")
        self.pagesstacked.addWidget(self.canadapage)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(770, 430, 84, 19))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pagesstacked.setCurrentIndex(1)
        self.displaytypeselector.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Testapp"))
        self.worldabysslabel.setText(_translate("MainWindow", "World Abyss"))
        self.continentsbutton.setText(_translate("MainWindow", "Continents"))
        self.citiesbutton.setText(_translate("MainWindow", "Cities"))
        self.countriesbutton.setText(_translate("MainWindow", "Countries"))
        self.label_user_icon.setText(_translate("MainWindow", "WM"))
        self.searchbar.setPlaceholderText(_translate("MainWindow", " Search here"))
        self.asiaword.setText(_translate("MainWindow", "ASIA"))
        self.antarticaword.setText(_translate("MainWindow", "ANTARTICA"))
        self.usaword.setText(_translate("MainWindow", "USA"))
        self.africaword.setText(_translate("MainWindow", "AFRICA"))
        self.southamericaword.setText(_translate("MainWindow", "SOUTH\n"
"AMERICA"))
        self.europeword.setText(_translate("MainWindow", "EUROPE"))
        self.australiabutton.setText(_translate("MainWindow", "AUSTRALIA"))
        self.label_15.setText(_translate("MainWindow", "South Korea"))
        self.label_4.setText(_translate("MainWindow", "Canada"))
        self.label_17.setText(_translate("MainWindow", "Russia"))
        self.label.setText(_translate("MainWindow", "Brazil"))
        self.label_2.setText(_translate("MainWindow", "USA"))
        self.label_21.setText(_translate("MainWindow", "Georgia"))
        self.label_20.setText(_translate("MainWindow", "Malaysia"))
        self.label_6.setText(_translate("MainWindow", "Finland"))
        self.label_8.setText(_translate("MainWindow", "China"))
        self.label_9.setText(_translate("MainWindow", "Spain"))
        self.label_12.setText(_translate("MainWindow", "Saudi Arabia"))
        self.label_14.setText(_translate("MainWindow", "Argentina"))
        self.label_19.setText(_translate("MainWindow", "Azerbaijian"))
        self.label_5.setText(_translate("MainWindow", "Belgium"))
        self.label_13.setText(_translate("MainWindow", "North Korea"))
        self.label_16.setText(_translate("MainWindow", "Czech Rep"))
        self.label_18.setText(_translate("MainWindow", "Italy"))
        self.label_11.setText(_translate("MainWindow", "Singapore"))
        self.label_3.setText(_translate("MainWindow", "Japan"))
        self.label_7.setText(_translate("MainWindow", "Germany"))
        self.label_22.setText(_translate("MainWindow", "Austria"))
        self.label_23.setText(_translate("MainWindow", "Indonesia"))
        self.label_24.setText(_translate("MainWindow", "Greece"))
        self.label_25.setText(_translate("MainWindow", "Netherlands"))
        self.displaytypeselector.setTabText(self.displaytypeselector.indexOf(self.byflag), _translate("MainWindow", "By flag"))
        self.label_27.setText(_translate("MainWindow", "Belgium"))
        self.label_28.setText(_translate("MainWindow", "Brazil"))
        self.label_26.setText(_translate("MainWindow", "USA"))
        self.label_29.setText(_translate("MainWindow", "Canada"))
        self.label_61.setText(_translate("MainWindow", "Germany"))
        self.label_59.setText(_translate("MainWindow", "Japan"))
        self.label_60.setText(_translate("MainWindow", "Finland"))
        self.label_58.setText(_translate("MainWindow", "China"))
        self.label_64.setText(_translate("MainWindow", "Czech Rep"))
        self.label_63.setText(_translate("MainWindow", "South Korea"))
        self.label_62.setText(_translate("MainWindow", "Russia"))
        self.label_65.setText(_translate("MainWindow", "Argentina"))
        self.label_71.setText(_translate("MainWindow", "Greece"))
        self.label_72.setText(_translate("MainWindow", "Italy"))
        self.label_70.setText(_translate("MainWindow", "Netherlands"))
        self.label_68.setText(_translate("MainWindow", "Austria"))
        self.label_67.setText(_translate("MainWindow", "Azerbaijian"))
        self.label_66.setText(_translate("MainWindow", "Georgia"))
        self.label_69.setText(_translate("MainWindow", "Indonesia"))
        self.label_73.setText(_translate("MainWindow", "Malaysia"))
        self.displaytypeselector.setTabText(self.displaytypeselector.indexOf(self.byname), _translate("MainWindow", "By name"))
        self.searchbar_2.setPlaceholderText(_translate("MainWindow", " Search here"))
        self.canadaword.setText(_translate("MainWindow", "CANADA"))
        self.famouswords.setText(_translate("MainWindow", "Famous for eternal snow, maple syrup, maple leaf, randonautica, \n"
"northern lights, politeness and Justin Trudeau."))
        self.countrydesc.setText(_translate("MainWindow", "Canada; French: is a country in the northern part of North America. Its ten\n"
"provinces and three territories extend from the Atlantic to the Pacific and\n"
"northward into the Arctic Ocean, covering 9.98 million square kilometres\n"
"(3.85 million square miles), making it the world\'s second-largest country\n"
"by total area and the fourth-largest country by land area."))
        self.montrealbutton.setText(_translate("MainWindow", "Montreal"))
        self.torontobutton.setText(_translate("MainWindow", "Toronto"))
        self.vancouverbutton.setText(_translate("MainWindow", "Vancouver"))
        self.label_10.setText(_translate("MainWindow", "USA"))
import resource_rc

# Configuration to run the application
os.environ['QT_MAC_WANTS_LAYER'] = '1'
myApp = QApplication(sys.argv)
w = QtWidgets.QMainWindow()
firstwindow = Ui_MainWindow()
firstwindow.setupUi(w)
firstwindow.countriesbutton.clicked.connect(lambda: firstwindow.pagesstacked.setCurrentIndex(1))
firstwindow.continentsbutton.clicked.connect(lambda: firstwindow.pagesstacked.setCurrentIndex(0))
firstwindow.canadabutton.clicked.connect(lambda: firstwindow.pagesstacked.setCurrentIndex(2))
w.show()
myApp.exec_()
sys.exit(0)